language: node_js
node_js:
- '0.10'
env:
- NODE_ENV=travis
services:
- mongodb
deploy:
  provider: heroku
  on: master
  api_key:
    secure: PPQUsaHSV8o852asNUtN+JORupOwclmMe+ACoJO4jEUIOL6RFcpuKY1+Rb5qoZM2CE49DICbiFE0SIlMcD3bd/o1zIlQUD9mZeBKl7lqTiionuUa8AeoU0BskgNMLcnAOx3XgVO2TGTjM7twL7wdDGpP8aGdzIaR/Ga68M2es/o=
